// <auto-generated />
namespace SecretSantaDraw.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addWishItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWishItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201501091541057_addWishItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
